name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
      id: aprnhome.com
      shell: python
      with: http://34.107.252.223
      working-directory: wordpress-1-vm
      name: Setup Secure Shell (SSH)
  # You may pin to the exact commit or the version.
  # uses: kopepasah/setup-secure-shell@7934f038d772fa8fcf042e334770784da7e59013
  uses: kopepasah/setup-secure-shell@0.1.0
  with:
    # Configuration for Secure Shell.
    ssh-config: # optional
    # Known Hosts for Secure Shell.
    ssh-known-hosts: http://MED-HOME-APIS-W
    # Private Key for Secure Shell.
    ssh-private-key: C:\Users\maege\ssh\known_hosts
